/*
 * Copyright 2016-2017 The Reaktivity Project
 *
 * The Reaktivity Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
scope scope1
{
    struct Flat
    {
        uint64 fixed1;
        uint16 fixed2 = 222;
        string variable1;
        octets extension;
    }

    struct Nested
    {
        uint64 fixed3 = 333;
        scope1::Flat variable;
    }

    struct FlatWithList
    {
        uint64 fixed1 = 111;
        list<string> variable1;
    }
}
